version: "2"
run:
  tests: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - misspell
    - mirror
    - modernize
    - nakedret
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    - wastedassign
  settings:
    gocritic:
      disabled-checks:
        - dupImport
        - hugeParam
        - rangeValCopy
        - unnamedResult
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
        - name: package-comments
          disabled: false
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
formatters:
  enable:
    - gofmt
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
